{
    "name": "Empresa Repartiments",
    "version": "1.0",
    "category": "Custom",
    "summary": "Gestión empresa de repartidores",
    "depends": ["base", "web"],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/menus.xml",
        "views/employee_views.xml",
        "views/vehicle_views.xml",
        "views/client_views.xml",
        "views/delivery_views.xml",
        "views/wizard_views.xml",
        "report/delivery_report.xml",
        "report/delivery_report_template.xml",
    ],
    "installable": True,
    "application": True,
}